# Generated by Django 4.1.3 on 2022-12-05 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_is_active_locationcourt_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courttype',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='location',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='location',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='locationcourt',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='locationcourt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
