# Generated by Django 4.1.3 on 2022-12-30 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_courttype_description_location_created_at_and_more'),
        ('profiles', '0004_userprofile_created_at_userprofile_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(choices=[('user_shown', 'User profile shown'), ('user_detail', 'User profile detail'), ('location_shown', 'Location shown'), ('location_detail', 'Location detail'), ('court_shown', 'Court shown'), ('court_detail', 'Court detail')], max_length=100)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.locationcourt')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='profiles.userprofile')),
            ],
        ),
    ]
