# Generated by Django 4.1.3 on 2022-12-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_courtschedule_is_active_alter_courtreservation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[(6, 'Saturday'), (2, 'Tuesday'), (7, 'Sunday'), (4, 'Thursday'), (5, 'Friday'), (1, 'Monday'), (3, 'Wednesday')], max_length=1),
        ),
    ]
