# Generated by Django 4.1.3 on 2022-12-05 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0004_alter_courtschedule_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courtscheduleexception',
            name='schedule',
        ),
        migrations.AddField(
            model_name='courtscheduleexception',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='courtscheduleexception',
            name='reserved_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_courts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('5', 'Friday'), ('2', 'Tuesday'), ('4', 'Thursday'), ('7', 'Sunday'), ('6', 'Saturday'), ('1', 'Monday'), ('3', 'Wednesday')], max_length=1),
        ),
    ]
