# Generated by Django 4.1.3 on 2022-12-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_remove_courtscheduleexception_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('3', 'Wednesday'), ('6', 'Saturday'), ('1', 'Monday'), ('7', 'Sunday'), ('4', 'Thursday'), ('2', 'Tuesday'), ('5', 'Friday')], max_length=1),
        ),
        migrations.DeleteModel(
            name='CourtScheduleException',
        ),
    ]
