# Generated by Django 4.1.3 on 2022-12-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_location_is_active_locationcourt_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0006_alter_courtschedule_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('5', 'Friday'), ('7', 'Sunday'), ('3', 'Wednesday'), ('1', 'Monday'), ('6', 'Saturday'), ('2', 'Tuesday'), ('4', 'Thursday')], max_length=1),
        ),
        migrations.CreateModel(
            name='CourtScheduleException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='locations.locationcourt')),
                ('reserved_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_courts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
