# Generated by Django 4.1.3 on 2022-12-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_alter_courtschedule_day_courtscheduleexception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('2', 'Tuesday'), ('6', 'Saturday'), ('3', 'Wednesday'), ('5', 'Friday'), ('1', 'Monday'), ('7', 'Sunday'), ('4', 'Thursday')], max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='courtreservation',
            unique_together={('schedule', 'date')},
        ),
    ]
