# Generated by Django 4.1.3 on 2022-12-05 17:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_alter_courtschedule_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtreservation',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='courtreservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courtreservation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courtschedule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courtschedule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='courtscheduleexception',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='courtscheduleexception',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('4', 'Thursday'), ('7', 'Sunday'), ('5', 'Friday'), ('1', 'Monday'), ('3', 'Wednesday'), ('6', 'Saturday'), ('2', 'Tuesday')], max_length=1),
        ),
    ]
