# Generated by Django 4.1.3 on 2022-12-05 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_courtreservation_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('2', 'Tuesday'), ('4', 'Thursday'), ('7', 'Sunday'), ('3', 'Wednesday'), ('1', 'Monday'), ('5', 'Friday'), ('6', 'Saturday')], max_length=1),
        ),
        migrations.AlterField(
            model_name='courtschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
