# Generated by Django 4.1.3 on 2022-12-05 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0010_alter_courtschedule_day_alter_courtschedule_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('6', 'Saturday'), ('4', 'Thursday'), ('7', 'Sunday'), ('3', 'Wednesday'), ('5', 'Friday'), ('2', 'Tuesday'), ('1', 'Monday')], max_length=1),
        ),
    ]
