# Generated by Django 4.1.3 on 2022-12-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0011_alter_courtschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('5', 'Friday'), ('2', 'Tuesday'), ('4', 'Thursday'), ('3', 'Wednesday'), ('7', 'Sunday'), ('1', 'Monday'), ('6', 'Saturday')], max_length=1),
        ),
    ]
