# Generated by Django 4.1.3 on 2022-12-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0012_alter_courtschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('4', 'Thursday'), ('1', 'Monday'), ('3', 'Wednesday'), ('5', 'Friday'), ('7', 'Sunday'), ('2', 'Tuesday'), ('6', 'Saturday')], max_length=1),
        ),
    ]
