# Generated by Django 4.1.3 on 2022-12-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0014_courtschedule_title_courtscheduleexception_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('3', 'Wednesday'), ('6', 'Saturday'), ('5', 'Friday'), ('2', 'Tuesday'), ('4', 'Thursday'), ('7', 'Sunday'), ('1', 'Monday')], max_length=1),
        ),
    ]
