# Generated by Django 4.1.3 on 2023-01-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0015_alter_courtschedule_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtschedule',
            name='day',
            field=models.CharField(choices=[('4', 'Thursday'), ('2', 'Tuesday'), ('1', 'Monday'), ('5', 'Friday'), ('6', 'Saturday'), ('3', 'Wednesday'), ('7', 'Sunday')], max_length=1),
        ),
    ]
